version: "3.8"

services:
  backend:
    build: ./xlr8-server
    container_name: xlr8_server
    restart: always
    environment:
      - FLASK_APP=run.py
      - FLASK_ENV=production
    ports:
      - "5000:5000"
    networks:
      - app_network
    volumes:
      - ./xlr8-server:/app 
      - ./xlr8-server/app/database.db:/instance/test.db 

  websocket:
    build: ./proxies
    container_name: websocket_server
    restart: always
    ports:
      - "9090:9090"
      - "3000:3000"
    networks:
      - app_network
    volumes:
      - ./proxies:/app
      - node_modules:/app/node_modules
      - ./proxies/cookies/user-profiles:/app/cookies/user-profiles
    shm_size: '2g'


      
networks:
  app_network:
    driver: bridge

volumes:
  node_modules:

    